---
title: "HW2_key"
author: "G3-"
date: ""
output:
  word_document: default
  pdf_document: default
---

```{r include=FALSE}
library(wooldridge)
library(dplyr)
```

# Question 1

```{r, comment=NA}
v1<- seq(1,17, by=4)
v1
```

# Question 2

## I) 

```{r,comment=NA}

A<- matrix(data= seq(20,39) , nrow = 4, ncol = 5, byrow = TRUE)
A

```

## II) 

```{r, comment=NA}

colnames(A) <- c('A','B','C','D','E')

A

```


## III) 

```{r, comment=NA}

B<- A[c(2,4)  , c(2,4) ]
B
```

## IV)

```{r, comment=NA}
t(B)
```


## V)

```{r, comment=NA}
B_inverse <- solve(B)
B_inverse
```


## VI)

```{r, comment=NA}
B %*% B_inverse
```
 
 the name of the above matrix is identity matrix. 
 
 -------------------------
 
# Question 3 

## I)

```{r, comment=NA}
df <- mtcars
head(df, 10)
```


## II)

```{r, comment=NA}
df1<- df %>% select(cyl, hp, wt, vs, am ,gear , mpg) %>% arrange(cyl) %>% head(5)
  
df1  
  
```






## III)

```{r, comment=NA}
df1 <- mutate(df1, gpm= round(1/mpg, 3))
head(df1, 5)
```


## IV) 

```{r}
str(df1)
```

## V)
 
```{r}
df1$cyl <-   factor(df1$cyl)
df1$am <-   factor(df1$am)
df1$gear <-   factor(df1$gear)
df1$vs <-   factor(df1$vs)

str(df1)
```
 
 

# Question 4 

## II


```{r}
df<- alcohol
df_filtered <- filter(df, status!=1)
table(df_filtered$status)
```












































